site_name: Epigenomics 2020

nav:
    - Welcome: welcome.md
    - About: about.md
    - Precourse Information: precourse.md
    - Schedule: schedule.md
    - Tutorials: tutorials.md


theme: readthedocs


