# conda requirements for all packages needed to run exercise integrating scATAC-seq and scRNA-seq data
# install with:  mamba env create -n epigenomics2022 -f environment_epigenomics2022.yaml
# then run: source activate epigenomics2022
name: epigenomics2022

channels:
### MAIN CONDA CHANNELS ###
  - conda-forge
  - bioconda
  - anaconda
  - defaults
  - r
### ADDITIONAL CONDA CHANNELS ###
  - rdonnelly
  - psi4
  - r_test
  - free
  - fastchan
  - ccordoba12
  - grst
  - Eugene_T
  - letaylor
  - ohsu-comp-bio

dependencies:
### GENERAL LIBRARIES ###
  - r-base=4.1.3
  - wget
  - compilers
  - pandoc=2.16.2
  - r-devtools
  - r-biocmanager
  # - rstudio-desktop=2022.12.0
  - openssl

### R BIOCONDUCTOR PACKAGES ##
  - bioconductor-rhdf5
  - bioconductor-genomeinfodb
  - bioconductor-ensdb.hsapiens.v75
  - bioconductor-org.hs.eg.db
  - bioconductor-tfbstools
  - bioconductor-bsgenome.hsapiens.ucsc.hg19
  - bioconductor-jaspar2020
  - bioconductor-biovizbase
  - bioconductor-motifmatchr
  - bioconductor-chromvar
  - bioconductor-rtracklayer
  - bioconductor-regioner
  - bioconductor-bsgenome.dmelanogaster.ucsc.dm3
  - bioconductor-bsgenome.mmusculus.ucsc.mm10
  - bioconductor-ensdb.mmusculus.v79
  - bioconductor-scrnaseq
  - bioconductor-singler
  - bioconductor-scran
### R CRAN PACKAGES ###
  - r-hdf5r
  - r-signac=1.7.0
  - r-tidyverse
  - r-patchwork
  - r-pheatmap
  - r-umap
### PYTHON LIBRARIES ###
  - python-annoy
  - multicore-tsne
  - requests
  - python-annoy
  - mnnpy
  - scanpy
  - scanorama
  - numba
  - llvmlite
  - python-igraph
  - umap-learn
  - louvain
  - leidenalg
  - matplotlib-venn
  - scrublet
  - gseapy
  - pybiomart
  - morphops
  - pip
  - pip:
    - gsea-api
